# Generated by Django 5.1.6 on 2025-03-07 07:50

import django.db.models.deletion
import eventi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="categoria",
            field=models.CharField(
                choices=[
                    (
                        "Iniziative promozionali in Italia e all'estero",
                        "Iniziative promozionali in Italia e all'estero",
                    ),
                    (
                        "Iniziative promozionali in loco",
                        "Iniziative promozionali in loco",
                    ),
                ],
                max_length=255,
                verbose_name="Categoria",
            ),
        ),
        migrations.CreateModel(
            name="EventFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=eventi.models.get_upload_path, verbose_name="File"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titolo del file"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("docx", "Word Document"),
                            ("pdf", "PDF Document"),
                            ("xlsx", "Excel Spreadsheet"),
                        ],
                        max_length=10,
                        verbose_name="Tipo di file",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrizione"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data caricamento"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_files_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Caricato da",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="eventi.event",
                        verbose_name="Evento correlato",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Evento",
                "verbose_name_plural": "File Eventi",
                "ordering": ["-created_at"],
            },
        ),
    ]
