# Generated by Django 5.1.6 on 2025-03-10 07:31

import eventi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventi", "0002_alter_event_categoria_eventfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfile",
            name="file",
            field=models.FileField(
                max_length=255,
                upload_to=eventi.models.get_upload_path,
                verbose_name="File",
            ),
        ),
    ]
