# Generated by Django 5.1.6 on 2025-03-10 07:44

import eventi.models
import eventi.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventi", "0003_alter_eventfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventfile",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=eventi.storage.BackblazeB2Storage(),
                upload_to=eventi.models.get_upload_path,
                verbose_name="File",
            ),
        ),
    ]
