# Generated by Django 5.1.6 on 2025-03-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventi", "0004_alter_eventfile_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nome Settore"
                    ),
                ),
            ],
            options={
                "verbose_name": "Settore",
                "verbose_name_plural": "Settori",
                "ordering": ["nome"],
            },
        ),
    ]
