# Generated by Django 5.1.6 on 2025-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventi", "0006_migrate_settore_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="privatistica",
            field=models.BooleanField(default=False, verbose_name="Privatistica"),
        ),
    ]
